// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 84830579f0
// Version Date: Thu Dec 31 05:37:46 UTC 2020

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/jjggzz/kit/transport/grpc"

	// This Service
	pb "videoWeb/notice-service/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC NoticeServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.NoticeServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// notice

		sendsms: grpctransport.NewServer(
			endpoints.SendSmsEndpoint,
			DecodeGRPCSendSmsRequest,
			EncodeGRPCSendSmsResponse,
			serverOptions...,
		),
		sendemail: grpctransport.NewServer(
			endpoints.SendEmailEndpoint,
			DecodeGRPCSendEmailRequest,
			EncodeGRPCSendEmailResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the NoticeServer interface
type grpcServer struct {
	sendsms   grpctransport.Handler
	sendemail grpctransport.Handler
}

// Methods for grpcServer to implement NoticeServer interface

func (s *grpcServer) SendSms(ctx context.Context, req *pb.SendSmsRequest) (*pb.SendSmsResponse, error) {
	_, rep, err := s.sendsms.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.SendSmsResponse), nil
}

func (s *grpcServer) SendEmail(ctx context.Context, req *pb.SendEmailRequest) (*pb.SendEmailResponse, error) {
	_, rep, err := s.sendemail.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.SendEmailResponse), nil
}

// Server Decode

// DecodeGRPCSendSmsRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC sendsms request to a user-domain sendsms request. Primarily useful in a server.
func DecodeGRPCSendSmsRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.SendSmsRequest)
	return req, nil
}

// DecodeGRPCSendEmailRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC sendemail request to a user-domain sendemail request. Primarily useful in a server.
func DecodeGRPCSendEmailRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.SendEmailRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCSendSmsResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain sendsms response to a gRPC sendsms reply. Primarily useful in a server.
func EncodeGRPCSendSmsResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.SendSmsResponse)
	return resp, nil
}

// EncodeGRPCSendEmailResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain sendemail response to a gRPC sendemail reply. Primarily useful in a server.
func EncodeGRPCSendEmailResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.SendEmailResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
