// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 51ceb8d33f
// Version Date: 2020-12-12T10:12:32Z

package main

import (
	"flag"

	// This Service
	"videoWeb/generate-service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
