// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 84830579f0
// Version Date: Thu Dec 31 05:37:46 UTC 2020

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/jjggzz/kit/transport/grpc"

	// This Service
	pb "videoWeb/video-service/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC VideoServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.VideoServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// video

		uploadvideo: grpctransport.NewServer(
			endpoints.UploadVideoEndpoint,
			DecodeGRPCUploadVideoRequest,
			EncodeGRPCUploadVideoResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the VideoServer interface
type grpcServer struct {
	uploadvideo grpctransport.Handler
}

// Methods for grpcServer to implement VideoServer interface

func (s *grpcServer) UploadVideo(ctx context.Context, req *pb.UploadVideoRequest) (*pb.UploadVideoResponse, error) {
	_, rep, err := s.uploadvideo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.UploadVideoResponse), nil
}

// Server Decode

// DecodeGRPCUploadVideoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC uploadvideo request to a user-domain uploadvideo request. Primarily useful in a server.
func DecodeGRPCUploadVideoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.UploadVideoRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCUploadVideoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain uploadvideo response to a gRPC uploadvideo reply. Primarily useful in a server.
func EncodeGRPCUploadVideoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.UploadVideoResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
