// Code generated by sqlxgen. DO NOT EDIT.
package repository

import (
	"time"
)

// 表名:video
// comment:
type Video struct {
	Id                int64      `db:"id" json:"id,omitempty"`                                 // 字段: [id] 类型:[bigint(20)] 注释: [主键ID]
	AccessKey         string     `db:"access_key" json:"accessKey,omitempty"`                  // 字段: [access_key] 类型:[varchar(64)] 注释: [业务key]
	CreateTime        *time.Time `db:"create_time" json:"createTime,omitempty"`                // 字段: [create_time] 类型:[datetime] 注释: [创建时间]
	UpdateTime        *time.Time `db:"update_time" json:"updateTime,omitempty"`                // 字段: [update_time] 类型:[datetime] 注释: [修改时间]
	DeleteStatus      int32      `db:"delete_status" json:"deleteStatus,omitempty"`            // 字段: [delete_status] 类型:[int(11)] 注释: [状态 0:未删除 1:已删除]
	CustomerId        int64      `db:"customer_id" json:"customerId,omitempty"`                // 字段: [customer_id] 类型:[bigint(20)] 注释: [客户主键id]
	VideoName         string     `db:"video_name" json:"videoName,omitempty"`                  // 字段: [video_name] 类型:[varchar(64)] 注释: [视频名称]
	VideoIntroduction string     `db:"video_introduction" json:"videoIntroduction,omitempty"`  // 字段: [video_introduction] 类型:[varchar(255)] 注释: [视频简介]
	VideoCoverPath    string     `db:"video_cover_path" json:"videoCoverPath,omitempty"`       // 字段: [video_cover_path] 类型:[varchar(255)] 注释: [视频封面路径]
	VideoSourcePath   string     `db:"video_source_path" json:"videoSourcePath,omitempty"`     // 字段: [video_source_path] 类型:[varchar(255)] 注释: [视频资源路径]
	VideoSize         int64      `db:"video_size" json:"videoSize,omitempty"`                  // 字段: [video_size] 类型:[bigint(20)] 注释: [视频大小]
	VideoThumbsCount  int64      `db:"video_thumbs_count" json:"videoThumbsCount,omitempty"`   // 字段: [video_thumbs_count] 类型:[bigint(20)] 注释: [视频点赞数]
	VideoPlayCount    int64      `db:"video_play_count" json:"videoPlayCount,omitempty"`       // 字段: [video_play_count] 类型:[bigint(20)] 注释: [视频播放数]
	VideoCommentCount int64      `db:"video_comment_count" json:"videoCommentCount,omitempty"` // 字段: [video_comment_count] 类型:[bigint(20)] 注释: [视频评论数]

}
