server:
  serverName: notice-service
  tcp:
    port: 10030

discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30
  nacos:
    address: 192.168.151.109:8848
    namespace: 73d8542f-4ccb-4f16-af3b-c104bee8af8f
    weight: 5

zipkin:
  address: 192.168.151.109:9411

email:
  qq:
    sender: 1945282561@qq.com
    password:
    addr: smtp.qq.com
    port: 587