// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 84830579f0
// Version Date: Thu Dec 31 05:37:46 UTC 2020

// Package grpc provides a gRPC client for the Video service.
package grpc

import (
	"context"
	"github.com/jjggzz/kit/endpoint"
	"github.com/jjggzz/kit/log"
	"github.com/jjggzz/kit/sd"
	"github.com/jjggzz/kit/sd/lb"
	kitzipkin "github.com/jjggzz/kit/tracing/zipkin"
	grpctransport "github.com/jjggzz/kit/transport/grpc"
	"github.com/openzipkin/zipkin-go"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"io"
	"time"

	// This Service
	pb "videoWeb/video-service/proto"
	"videoWeb/video-service/svc"
)

func NewLoadBalanceClient(instancer sd.Instancer, tracer *zipkin.Tracer, logger log.Logger) (pb.VideoServer, error) {
	options := []grpctransport.ClientOption{}
	if tracer != nil {
		options = append(options, kitzipkin.GRPCClientTrace(tracer))
	}

	var endpoints svc.Endpoints
	{
		factory := factoryGRPCFor(svc.MakeUploadVideoEndpoint, options...)
		endpointer := sd.NewEndpointer(instancer, factory, logger)
		balancer := lb.NewRoundRobin(endpointer)
		endpoints.UploadVideoEndpoint = lb.Retry(3, time.Millisecond*3000, balancer)
	}

	return endpoints, nil
}

func factoryGRPCFor(makeEndpoint func(pb.VideoServer) endpoint.Endpoint, clientOptions ...grpctransport.ClientOption) sd.Factory {
	return func(instance string) (endpoint.Endpoint, io.Closer, error) {
		conn, err := grpc.Dial(instance, grpc.WithInsecure())
		if err != nil {
			return nil, nil, err
		}
		server, err := New(conn, clientOptions)
		return makeEndpoint(server), conn, err
	}
}

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, clientOptions []grpctransport.ClientOption, options ...ClientOption) (pb.VideoServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions = append(clientOptions, grpctransport.ClientBefore(contextValuesToGRPCMetadata(cc.headers)))

	//clientOptions := []grpctransport.ClientOption{
	//	grpctransport.ClientBefore(
	//		contextValuesToGRPCMetadata(cc.headers)),
	//}
	var uploadvideoEndpoint endpoint.Endpoint
	{
		uploadvideoEndpoint = grpctransport.NewClient(
			conn,
			"proto.Video",
			"UploadVideo",
			EncodeGRPCUploadVideoRequest,
			DecodeGRPCUploadVideoResponse,
			pb.UploadVideoResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		UploadVideoEndpoint: uploadvideoEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCUploadVideoResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC uploadvideo reply to a user-domain uploadvideo response. Primarily useful in a client.
func DecodeGRPCUploadVideoResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.UploadVideoResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCUploadVideoRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain uploadvideo request to a gRPC uploadvideo request. Primarily useful in a client.
func EncodeGRPCUploadVideoRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.UploadVideoRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
