# 服务基本配置
server:
  serverName: video-service
  tcp:
    port: 10050

# 服务注册与发现
discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30
  nacos:
    address: 192.168.151.109:8848
    namespace: 73d8542f-4ccb-4f16-af3b-c104bee8af8f
    weight: 5

# 数据库
db:
  mysql:
    host: localhost
    port: 3306
    schema: video
    username: root
    password: 123456

# redis配置
redis:
  address: localhost:6379
  maxIdle: 8
  maxActive: 50
  idleTimeout: 100

# 链路追踪服务地址
zipkin:
  address: 192.168.151.109:9411


