server:
  serverName: generate-service
  tcp:
    port: 10010

discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30
  nacos:
    address: 192.168.1.102:8848
    namespace: c6f706d8-6ebf-4c6c-ab3b-24a573806a8f
    weight: 5

workId: 1

zipkin:
  address: 192.168.1.102:9411