server:
  serverName: generate-service
  tcp:
    port: 8888

discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30

workId: 1

zipkin:
  address: 192.168.151.109:9411