// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 1b850652b8
// Version Date: Sun Dec 13 03:19:12 UTC 2020

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "videoWeb/customer-service/proto"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	RegisterByPhoneEndpoint        endpoint.Endpoint
	LoginByPhoneEndpoint           endpoint.Endpoint
	GetCustomerInfoByTokenEndpoint endpoint.Endpoint
}

// Endpoints

func (e Endpoints) RegisterByPhone(ctx context.Context, in *pb.RegisterByPhoneRequest) (*pb.RegisterByPhoneResponse, error) {
	response, err := e.RegisterByPhoneEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.RegisterByPhoneResponse), nil
}

func (e Endpoints) LoginByPhone(ctx context.Context, in *pb.LoginByPhoneRequest) (*pb.LoginByPhoneResponse, error) {
	response, err := e.LoginByPhoneEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.LoginByPhoneResponse), nil
}

func (e Endpoints) GetCustomerInfoByToken(ctx context.Context, in *pb.GetCustomerInfoByTokenRequest) (*pb.GetCustomerInfoByTokenResponse, error) {
	response, err := e.GetCustomerInfoByTokenEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetCustomerInfoByTokenResponse), nil
}

// Make Endpoints

func MakeRegisterByPhoneEndpoint(s pb.CustomerServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.RegisterByPhoneRequest)
		v, err := s.RegisterByPhone(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeLoginByPhoneEndpoint(s pb.CustomerServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.LoginByPhoneRequest)
		v, err := s.LoginByPhone(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetCustomerInfoByTokenEndpoint(s pb.CustomerServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetCustomerInfoByTokenRequest)
		v, err := s.GetCustomerInfoByToken(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"RegisterByPhone":        {},
		"LoginByPhone":           {},
		"GetCustomerInfoByToken": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "RegisterByPhone" {
			e.RegisterByPhoneEndpoint = middleware(e.RegisterByPhoneEndpoint)
		}
		if inc == "LoginByPhone" {
			e.LoginByPhoneEndpoint = middleware(e.LoginByPhoneEndpoint)
		}
		if inc == "GetCustomerInfoByToken" {
			e.GetCustomerInfoByTokenEndpoint = middleware(e.GetCustomerInfoByTokenEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"RegisterByPhone":        {},
		"LoginByPhone":           {},
		"GetCustomerInfoByToken": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "RegisterByPhone" {
			e.RegisterByPhoneEndpoint = middleware("RegisterByPhone", e.RegisterByPhoneEndpoint)
		}
		if inc == "LoginByPhone" {
			e.LoginByPhoneEndpoint = middleware("LoginByPhone", e.LoginByPhoneEndpoint)
		}
		if inc == "GetCustomerInfoByToken" {
			e.GetCustomerInfoByTokenEndpoint = middleware("GetCustomerInfoByToken", e.GetCustomerInfoByTokenEndpoint)
		}
	}
}
