// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: a56d9007fd
// Version Date: Fri Dec 18 09:51:12 UTC 2020

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "videoWeb/sms-service/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC SmsServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.SmsServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// sms

		sendsms: grpctransport.NewServer(
			endpoints.SendSmsEndpoint,
			DecodeGRPCSendSmsRequest,
			EncodeGRPCSendSmsResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the SmsServer interface
type grpcServer struct {
	sendsms grpctransport.Handler
}

// Methods for grpcServer to implement SmsServer interface

func (s *grpcServer) SendSms(ctx context.Context, req *pb.SendSmsRequest) (*pb.SendSmsResponse, error) {
	_, rep, err := s.sendsms.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.SendSmsResponse), nil
}

// Server Decode

// DecodeGRPCSendSmsRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC sendsms request to a user-domain sendsms request. Primarily useful in a server.
func DecodeGRPCSendSmsRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.SendSmsRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCSendSmsResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain sendsms response to a gRPC sendsms reply. Primarily useful in a server.
func EncodeGRPCSendSmsResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.SendSmsResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
