// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: a56d9007fd
// Version Date: Fri Dec 18 09:51:12 UTC 2020

// Package grpc provides a gRPC client for the Email service.
package grpc

import (
	"context"
	"github.com/go-kit/kit/endpoint"
	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/sd"
	"github.com/go-kit/kit/sd/lb"
	kitzipkin "github.com/go-kit/kit/tracing/zipkin"
	grpctransport "github.com/go-kit/kit/transport/grpc"
	"github.com/openzipkin/zipkin-go"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"io"
	"time"

	// This Service
	pb "videoWeb/email-service/proto"
	"videoWeb/email-service/svc"
)

func NewLoadBalanceClient(instancer sd.Instancer, tracer *zipkin.Tracer, logger log.Logger) (pb.EmailServer, error) {
	options := []grpctransport.ClientOption{}
	if tracer != nil {
		options = append(options, kitzipkin.GRPCClientTrace(tracer))
	}

	var endpoints svc.Endpoints
	{
		factory := factoryGRPCFor(svc.MakeSendEmailEndpoint, options...)
		endpointer := sd.NewEndpointer(instancer, factory, logger)
		balancer := lb.NewRoundRobin(endpointer)
		endpoints.SendEmailEndpoint = lb.Retry(3, time.Millisecond*3000, balancer)
	}

	return endpoints, nil
}

func factoryGRPCFor(makeEndpoint func(pb.EmailServer) endpoint.Endpoint, clientOptions ...grpctransport.ClientOption) sd.Factory {
	return func(instance string) (endpoint.Endpoint, io.Closer, error) {
		conn, err := grpc.Dial(instance, grpc.WithInsecure())
		if err != nil {
			return nil, nil, err
		}
		server, err := New(conn, clientOptions)
		return makeEndpoint(server), conn, err
	}
}

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, clientOptions []grpctransport.ClientOption, options ...ClientOption) (pb.EmailServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions = append(clientOptions, grpctransport.ClientBefore(contextValuesToGRPCMetadata(cc.headers)))

	//clientOptions := []grpctransport.ClientOption{
	//	grpctransport.ClientBefore(
	//		contextValuesToGRPCMetadata(cc.headers)),
	//}
	var sendemailEndpoint endpoint.Endpoint
	{
		sendemailEndpoint = grpctransport.NewClient(
			conn,
			"proto.Email",
			"SendEmail",
			EncodeGRPCSendEmailRequest,
			DecodeGRPCSendEmailResponse,
			pb.SendEmailResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		SendEmailEndpoint: sendemailEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCSendEmailResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC sendemail reply to a user-domain sendemail response. Primarily useful in a client.
func DecodeGRPCSendEmailResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.SendEmailResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCSendEmailRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain sendemail request to a gRPC sendemail request. Primarily useful in a client.
func EncodeGRPCSendEmailRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.SendEmailRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
