server:
  serverName: verify-service
  tcp:
    port: 9999

discovery:
  consul:
    address: 192.168.1.102:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30

redis:
  address: 192.168.1.102:6379

zipkin:
  address: 192.168.1.102:9411