server:
  serverName: verify-service
  tcp:
    port: 10040

discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30
  nacos:
    address: 192.168.1.102:8848
    namespace: c6f706d8-6ebf-4c6c-ab3b-24a573806a8f
    weight: 5

redis:
  address: localhost:6379
  maxIdle: 8
  maxActive: 50
  idleTimeout: 100

zipkin:
  address: 192.168.1.102:9411

noticeService: notice-service