server:
  serverName: verify-service
  tcp:
    port: 9999

discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30

redis:
  address: localhost:3306

zipkin:
  address: 192.168.151.109:9411