server:
  serverName: verify-service
  tcp:
    port: 9999

discovery:
  consul:
    address: 192.168.1.102:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30

redis:
  address: localhost:6379
  maxIdle: 8
  maxActive: 50
  idleTimeout: 100

zipkin:
  address: 192.168.1.102:9411