server:
  serverName: customer-service
  tcp:
    port: 7777

discovery:
  consul:
    address: 192.168.151.109:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30

# 数据库
db:
  mysql:
    host: localhost
    port: 3306
    schema: customer
    username: root
    password: 123456

redis:
  address: localhost:6379
  maxIdle: 8
  maxActive: 50
  idleTimeout: 100

generateServerName: generate-service
verifyServerName: verify-service

zipkin:
  address: 192.168.151.109:9411